use PIZZAS_R_US;
DROP SCHEMA PIZZAS_R_US;
DROP TABLE dinein;
DROP TABLE delivery;
DROP TABLE pickup;
DROP TABLE discountorder;
DROP TABLE pizzadiscount;
DROP TABLE discount;
DROP TABLE pizzatopping;
DROP TABLE pizza;
DROP TABLE ordert;
DROP TABLE customer;
DROP TABLE baseprice;
DROP TABLE topping;